DROP TABLE ROLE CASCADE;
DROP TABLE RESOURCE CASCADE;

ALTER TABLE USER_RESOURCE DROP COLUMN RESOURCE_ID;
ALTER TABLE USER_RESOURCE DROP COLUMN ROLE_ID;

ALTER TABLE USER_RESOURCE ADD RESOURCE VARCHAR(255);
ALTER TABLE USER_RESOURCE ADD ROLE VARCHAR(255);

CREATE INDEX USER_RESOURCE_RESOURCE_ROLE_index ON USER_RESOURCE (RESOURCE, ROLE);

DELETE FROM USER_RESOURCE;
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(1, 1, 'A', 'READ');
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(2, 1, 'A.B.C', 'WRITE') ;
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(3, 2,'A', 'EXECUTE');
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(4,2,'A', 'READ');
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(5, 2,'A', 'WRITE');
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(6,2,'A.B', 'READ');
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(7,3,'A', 'EXECUTE');
INSERT INTO USER_RESOURCE(ID, USER_ID, RESOURCE, ROLE) VALUES(8,1,'A', 'EXECUTE');