CREATE TABLE USER (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, LOGIN VARCHAR(10) UNIQUE, HASH_PASSWORD VARCHAR(255), SALT VARCHAR(255));
CREATE TABLE ROLE (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, ROLE_NAME VARCHAR(30) UNIQUE);
CREATE TABLE RESOURCE (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, PATH VARCHAR(255) UNIQUE);
CREATE TABLE USER_RESOURCE (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, USER_ID INT, RESOURCE_ID INT, ROLE_ID INT);
CREATE TABLE USER_SESSION (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, ACCESS_ID INT, START_DATE DATE, END_DATE DATE, VOLUME INT);